site_name: Guardians of the Horde Incursions Wiki
pages:
  - Home: index.md
  - FCs: fcs.md
  - Fittings:
    - Fittings Overview: fittings.md
    - Logistics: logi.md
    - T3Cs:
      - T3C Overview: T3Cs.md
      - Loki: loki.md
      - Tengu: tengu.md
    - Battleships: battleships.md
    - Carriers: carriers.md
    - Supers: supers.md
    - Titans: titans.md
  - Contributing: contrib.md
theme: readthedocs
