site_name: Guardians of the Horde Incursions Wiki
pages:
  - Home: index.md
  - Support: support.md
  - FCs: fcs.md
  - Fittings:
    - Fittings Overview: fittings.md
    - Logistics: logi.md
    - T3Cs:
      - T3C Overview: T3Cs.md
      - Logi: t3logi.md
      - Loki: loki.md
      - Tengu: tengu.md
    - Battleships: battleships.md
    - Capitals:
      - Overview: capitals.md
      - Carriers: carriers.md
      - Dreadnoughts: dreads.md
      - Faxes: faxes.md
      - Supers: supers.md
      - Titans: titans.md
  - Contributing: contrib.md
theme: readthedocs
